### ISSUE TITLE
CDL Values descriptions are coming incorrect with respect to Headings 

### ISSUE THREAD

**Issue by gggodhwani** [CivicDataLab/civicdatalab.github.io#114]
![image](https://user-images.githubusercontent.com/2306011/121779098-9be71b00-cbb7-11eb-995d-fd7b79917796.png)
![image](https://user-images.githubusercontent.com/2306011/121779115-b4efcc00-cbb7-11eb-84d4-98aae61dc0a9.png)

**Comment by akkisagiraju** [comment]
@apoorv74 Can we have some write up for the Experimentation and Innovation value?

**Comment by apoorv74** [comment]
@akkisagiraju 

> Exploration and Experimentation are intrinsic to our work, from day to day tasks to organizational conducts. By encouraging experiments, we foster a culture of research that defines who we are as an organization. What works is retained and reproduced and what doesn’t is yet another lesson learned.
Innovation thrives when we continuously experiment and challenge ourselves. So as we ensure experimentation, we inherently encourage innovation.

You can check the descriptions from the old website [here](https://github.com/CivicDataLab/old-website/blob/master/values.html)

**Comment by akkisagiraju** [comment]
PR #116 fixes this.

**Comment by apoorv74** [comment]
Feedback

> We understand feedback is powerful as it serves as a guide to assist people to know how they and others perceive their performance. We regularly exchange feedback among partner organisations, communities and other people we work with. It helps us achieve more collaboration and explore new opportunities. We also practice effective listening and proactive communication as they are essential for effective problem-solving in an organization.

Openness

> "_A piece of knowledge, unlike a piece of physical property, can be shared by large groups of people without making anybody poorer._" - Aaron Swartz 
At CivicDataLab, we exercise openness as core to our work and encourage our partners to collaborate in open as well. We are committed to sharing our learnings and failures to grow together. We believe that our world can become a much better place if we start thinking and working in open.
