### ISSUE TITLE
How can we better showcase the various civic engagement initiatives on the website

### ISSUE THREAD

**Issue by apoorv74** [CivicDataLab/civicdatalab.github.io#129]
Suggestion: We need a page on our website to better showcase our engagement initiatives and disseminate our works. All links and materials which could be accessed by differnt people (non tech/ data specialist actors).  The page could also work as a portfolio we could share with academia/ organization etc to push for workshops and programs.

**Comment by apoorv74** [comment]
Shared by @Kabeer3 

![Braindump](https://user-images.githubusercontent.com/5118689/131441939-a97babde-7ab7-46b8-9564-66a78fc8a0cf.jpg)

To better showcase our engagement initiatives and disseminate our works. Could also work as a portfolio we could share with academia/ organization etc to push for workshops.

**Comment by PixeledCode** [comment]
#219
