### ISSUE TITLE
Low resolution CivicDataLab logo in the website footer

### ISSUE THREAD

**Issue by gggodhwani** [CivicDataLab/civicdatalab.github.io#140]
The resolution of the logo is much lower than its size in the website's footer.
![image](https://user-images.githubusercontent.com/2306011/140720428-7fcd8dff-ca33-4326-86ed-888ce81f6f06.png)

**Comment by PixeledCode** [comment]
thanks for pointing it out. I will need the original file of the logo, hopefully as an SVG. @gggodhwani

**Comment by PixeledCode** [comment]
fixed in latest merge https://github.com/CivicDataLab/civicdatalab.github.io/commit/893fe4eb9dabc6cf61fde4c017af0e6c9d6ee465
