### ISSUE TITLE
Fix bugs in Event Page

### ISSUE THREAD

**Issue by PixeledCode** [CivicDataLab/civicdatalab.github.io#223]
- [x] Navigation indicator that event is selected is removed on selection of filter
- [x] There is a page jump on change of filters to Upcoming Events, this can be fixed by setting a min height

**Comment by vishwa-akshat** [comment]
hey @PixeledCode does this still need to be resolved? if yes I would love to do it

**Comment by aashimgarg** [comment]
@vishwa-akshat you can work on this.

**Comment by Pavan-Nambi** [comment]
hey can i work on this? i know this is assigned to someone else but this doesn't seem to be done and its been 2 months so..? @PixeledCode  @aashimgarg

**Comment by Pavan-Nambi** [comment]
btw this website is really cool. i know this is a company website but i rarely see a startup having this level of  good and attractive ui 🎉

**Comment by PixeledCode** [comment]
> hey can i work on this? i know this is assigned to someone else but this doesn't seem to be done and its been 2 months so..? @PixeledCode @aashimgarg

@Pavan-Nambi go ahead

**Comment by Pavan-Nambi** [comment]
okay thanks , btw what is the node js version required? it's not mentioned anywhere in README latest(20) works? @PixeledCode

**Comment by PixeledCode** [comment]
> okay thanks , btw what is the node js version required? it's not mentioned anywhere in README latest(20) works? @PixeledCode

well the gatsby version is pretty old, I would suggest node v16 if 20 doesn't work

**Comment by Pavan-Nambi** [comment]
hey , where can i filter upcoming events...?

**Comment by Pavan-Nambi** [comment]
I believe u meant this one? `events/data-dialogues/`

**Comment by PixeledCode** [comment]
> I believe u meant this one? `events/data-dialogues/`

yeah, upcoming event section is removed but problem is still there for page jump. This can be fixed by min-height

**Comment by PixeledCode** [comment]
closed in #232 thanks @Pavan-Nambi
