### ISSUE TITLE
Migrate gatsby and all dependencies to new versions

### ISSUE THREAD

**Issue by Pavan-Nambi** [CivicDataLab/civicdatalab.github.io#233]

**Comment by Pavan-Nambi** [comment]
@PixeledCode  hey , can i do this?

(this might take long , i'll do whenever i am free)

**Comment by PixeledCode** [comment]
> @PixeledCode hey , can i do this?
> 
> (this might take long , i'll do whenever i am free)

sure go ahead, no hurries on this one

**Comment by PixeledCode** [comment]
@Pavan-Nambi sorry, closing this issue. We are migrating on a new version of this website. Basically a revamp. Don't want you to spend your time on something that will be replaced soon

**Comment by Pavan-Nambi** [comment]
> @Pavan-Nambi sorry, closing this issue. We are migrating on a new version of this website. Basically a revamp. Don't want you to spend your time on something that will be replaced soon

okay no issues, i'd love to help with new website! ping me if u can.

apart from that feel free to assign me to any issue in future.  i checked other repos but i guess all issues are assigned to company specific ppl so didn't bothered to comment.
