### ISSUE TITLE
Some filters in Resource page are not working

### ISSUE THREAD

**Issue by PixeledCode** [CivicDataLab/civicdatalab.github.io#236]
Atleast Guidebook filter is not working. There are multiple entries for that filter.

<img width="1172" alt="Screenshot 2024-02-05 at 5 50 42 PM" src="https://github.com/CivicDataLab/civicdatalab.github.io/assets/22215209/b3297ba9-b78a-428e-85fb-f26c7c119af8">

**Comment by aashimgarg** [comment]
Fixed!
